<a href="https://colab.research.google.com/github/HarsiratSinghJouhal/ML-with-pytorch/blob/main/00_pytorch_thefundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch TheFundamentals
Reference Book: https://www.learnpytorch.io/

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

##Introduction to Tensors
###Creating Tensors
PyTorch Tensors are created using torch.tensor()

In [22]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [23]:
scalar.ndim

0

In [24]:
scalar.shape

torch.Size([])

Get scalar back as Python **int**

In [7]:
scalar.item()

7

In [8]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

Get vector back as a Python list

In [27]:
vector.tolist()

[7, 7]

In [10]:
#MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
MATRIX[1]

tensor([ 9, 10])

In [34]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [35]:
TENSOR.ndim

3

In [36]:
TENSOR.shape

torch.Size([1, 3, 3])

In [38]:
TENSOR.tolist()

[[[1, 2, 3], [3, 6, 9], [2, 4, 5]]]